app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

scuf:
    resource: '@ScufBundle/Controller/DefaultController.php'
    type:     annotation

access:
    type: rest
    resource: ScufBundle\Controller\AccessController

setting:
    type: rest
    resource: ScufBundle\Controller\SettingController

user:
    type: rest
    resource: ScufBundle\Controller\UserController

action:
    type: rest
    resource: ScufBundle\Controller\ActionController

event:
    type: rest
    resource: ScufBundle\Controller\EventController

section:
    type: rest
    resource: ScufBundle\Controller\SectionController

auth-tokens:
    type: rest
    resource: ScufBundle\Controller\AuthTokenController